### ISSUE TITLE
InvalidRevisionException for RevisionLocation

### ISSUE THREAD

**Issue by furybyname** [drone-plugins/drone-codedeploy#4]
When revision_type is 'GitHub'
InvalidRevisionException: Only GitHubLocation may be specified if RevisionType is GitHub.

When revision_type is 'S3'
InvalidRevisionException: Only S3Location may be specified if RevisionType is S3.

It looks like the locations will have to be added conditionally instead of both being populated.

**Comment by tboerger** [comment]
Thanks for testing, I will create a fix PR.

**Comment by tboerger** [comment]
I have opened a pull request to fix this issue. Should be cool if you can test this one again.
