### ISSUE TITLE
List it on plugins.drone.io?

### ISSUE THREAD

**Issue by evert0n** [drone-plugins/drone-codedeploy#9]
Any reason why this plugin is not listed on  plugins.drone.io catalog?

**Comment by tboerger** [comment]
Yes, the reason is that nobody updated this plugin to be compatible with drone >= 0.5

**Comment by evert0n** [comment]
I see, I'm not a go-lang dev yet but as soon I feel more confidence with it I can try if this is still open. Thanks

**Comment by tboerger** [comment]
If there is a need for this plugin maybe one of the contributors is willing to update it for drone >= 0.5?

/cc @drone-plugins/maintainers

**Comment by tboerger** [comment]
Closing this issue for now, it will be listed on plugin index when it's compatible to current Drone versions.
